import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import QueryProvider from '@/components/business/QueryProvider';
import GitHubRateLimit from '@/components/github/GitHubRateLimit';

import '@/styles/globals.css';

const notoSansKr = Noto_Sans_KR({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansKr.className}>
        <QueryProvider>{children}</QueryProvider>
        <GitHubRateLimit />
      </body>
    </html>
  );
}
